swagger: "2.0"
info:
  version: "1.0.0"
  title: Server API
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /servers:
    get:
      summary: Get all servers
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Server"
    post:
      summary: Add a new server
      parameters:
        - in: body
          name: server
          description: The server to add
          required: true
          schema:
            $ref: "#/definitions/Server"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/Server"
  /servers/{id}:
    get:
      summary: Get a server by ID
      parameters:
        - in: path
          name: id
          description: The ID of the server
          required: true
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Server"
        "404":
          description: Not found
    delete:
      summary: Delete a server by ID
      parameters:
        - in: path
          name: id
          description: The ID of the server
          required: true
          type: string
      responses:
        "204":
          description: No content
  /servers/search/{name}:
    get:
      summary: Find servers by name
      parameters:
        - in: path
          name: name
          description: The name of the server to search for
          required: true
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Server"
        "404":
          description: Not found
definitions:
  Server:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      language:
        type: string
      framework:
        type: string
    required:
      - id
      - name
      - language
      - framework
